CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE EMPLOYEE(
ID INT,
NAME VARCHAR(50),
GENDER VARCHAR(50),
SALARY INT ,
DEPARTMENT VARCHAR(50)
);

INSERT INTO employee VALUES
  (1, 'jalpesh', 'Male', 5000, 'Sales'),
  (2, 'sneha', 'Female', 6000, 'HR'),
  (3, 'Karti', 'Female', 7500, 'IT'),
  (4, 'suman', 'Male', 6500, 'Marketing'),
  (5, 'viha', 'Female', 5500, 'Finance'),
  (6, 'vishal', 'Male', 8000, 'Sales'),
  (7, 'Viki', 'Male', 7200, 'HR'),
  (8, 'Viysni', 'Female', 6600, 'IT'),
  (9, 'alpa', 'Female', 5400, 'Marketing'),
  (10, 'aesha', 'Female', 6300, 'Finance'),
  (11, 'vishal', 'Male', 5700, 'Sales'),
  (12, 'Pratik', 'Male', 7000, 'HR'),
  (13, 'janvi', 'Female', 7100, 'IT'),
  (14, 'prapti', 'Female', 6800,'Marketing'),
  (15, 'axil', 'Male', 5000, 'Finance');

SELECT * FROM EMPLOYEE;

SELECT DEPARTMENT,SUM(SALARY) AS SALARY_SUM FROM EMPLOYEE GROUP BY DEPARTMENT;

SELECT DEPARTMENT,SUM(SALARY) AS SALARY_SUM FROM EMPLOYEE GROUP BY DEPARTMENT WITH ROLLUP;

/*ROLLUP OPERATIONS*/

/*COALESCE() FUNCTION*/

SELECT COALESCE(DEPARTMENT,'ALL DEPARTMENTS')AS DEPARTMENT,
SUM(SALARY) AS SALARY_SUM FROM EMPLOYEE
 GROUP BY DEPARTMENT WITH ROLLUP;
 

 
  SELECT COALESCE(DEPARTMENT,'ALL DEPARTMENTS')AS DEPARTMENT,
  COALESCE(GENDER,'ALL GENDERS')AS GENDER,
  SUM(SALARY) AS SALARY_SUM FROM EMPLOYEE
 GROUP BY DEPARTMENT,GENDER WITH ROLLUP;
 
 /*QUERY NOT WORINKG IN WORKBENCH*/
 
  SELECT COALESCE(DEPARTMENT,'ALL DEPARTMENTS')AS DEPARTMENT,
  COALESCE(GENDER,'ALL GENDERS')AS GENDER,
  SUM(SALARY) AS SALARY_SUM FROM EMPLOYEE
  GROUP BY CUBE (DEPARTMENT,GENDER);
 
 SELECT COALESCE(DEPARTMENT,'ALL DEPARTMENTS')AS DEPARTMENT,
  COALESCE(GENDER,'ALL GENDERS')AS GENDER,
  SUM(SALARY) AS SALARY_SUM FROM EMPLOYEE
 GROUP BY DEPARTMENT,GENDER WITH CUBE;
 